FROM ubuntu:18.04
# Để khi chạy các câu lệnh có prompt thì nó sẽ bỏ qua và cài đặt luôn
# ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -y python3-dev

# RUN apt install -y python3-dev
